#!/bin/bash

#SBATCH --nodes=1

#SBATCH --time=5
#SBATCH --job-name=heated_plate_pra01
#SBATCH --output=heated_plate_pthreads_out

g++ -Wall -O3 -std=c++11 -o heated_plate ../src/heated_plate_pthreads.cpp
srun ./heated_plate 1024 128 40.0 1 file_1
srun ./heated_plate 1024 128 40.0 2 file_1
srun ./heated_plate 1024 128 40.0 4 file_1
srun ./heated_plate 1024 128 40.0 8 file_1
srun ./heated_plate 1024 128 40.0 16 file_1
srun ./heated_plate 1024 128 40.0 32 file_1



